'use client'

import { useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { BadgeCheck, BriefcaseBusiness, Check, Clock3, EyeOff, GraduationCap, IndianRupee, ShieldCheck, Sparkles } from 'lucide-react'
import { AppShell } from '@/components/app-shell'
import { ChartFrame, ConsentBadge, DetailSheet, PageHeader, SectionCard, StatusPill } from '@/components/work-sync'
import { getTraineePassport, trainees, type OutcomeEvent } from '@/lib/mock-data'
import { CHART_SEMANTIC, CHART_SERIES } from '@/theme'

const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value)
const dates = (value?: string) => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)) : 'Date not recorded'
const lifecycle = ['Train', 'Certify', 'Place', 'Verify', 'Retain', 'Progress']
const lifecycleFor = (outcomes: OutcomeEvent[], verified: boolean) => [true, true, outcomes.length > 0, verified, outcomes.some((event) => event.outcomeType === 'wage_employment'), outcomes.some((event) => event.outcomeType === 'wage_update')]

export default function TraineePage() {
  const [traineeId, setTraineeId] = useState('KP-0001')
  const [maskSheet, setMaskSheet] = useState(false)
  const passport = getTraineePassport(traineeId) ?? getTraineePassport('KP-0001')!
  const { trainee, consent, outcomes, verification } = passport
  const isConsentActive = consent.consentStatus === 'active'
  const verified = verification?.verificationStatus === 'verified'
  const lifecycleState = lifecycleFor(outcomes, verified)
  const wageEvents = outcomes.filter((event) => event.outcomeType === 'wage_update' && event.monthlyWage).sort((a, b) => a.eventDate.localeCompare(b.eventDate))
  const wageData = wageEvents.map((event) => ({ date: dates(event.eventDate), wage: event.monthlyWage ?? 0 }))
  const employmentEvents = outcomes.filter((event) => ['wage_employment', 'job_change', 'wage_update'].includes(event.outcomeType)).sort((a, b) => a.eventDate.localeCompare(b.eventDate))
  const milestones = useMemo(() => [{ label: '1 month', state: outcomes.length ? 'met' : 'pending' }, { label: '3 months', state: verified ? 'met' : 'pending' }, { label: '6 months', state: trainee.status === 'retained' ? 'met' : 'pending' }, { label: '12 months', state: trainee.status === 'retained' ? 'pending' : 'not yet due' }] as const, [outcomes.length, trainee.status, verified])
  const masked = !isConsentActive
  return <AppShell><main className="mx-auto flex max-w-[1240px] flex-col gap-6 px-4 py-6 sm:px-6 lg:px-8"><PageHeader eyebrow="Trainee outcome passport" title="Trainee Outcome Passport" description="What can this learner prove about their training and employment?" actions={<label className="flex items-center gap-2 text-meta text-muted-foreground">View learner<select value={traineeId} onChange={(event) => setTraineeId(event.target.value)} className="rounded-control border border-border bg-surface px-3 py-2 text-foreground focus-visible:outline-2 focus-visible:outline-brand">{trainees.slice(0, 6).map((item) => <option key={item.traineeId} value={item.traineeId}>{item.traineeId}</option>)}</select></label>} />
    <SectionCard title="Identity and consent" description="A single joined record across training, certification, and outcomes."><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-serif text-2xl text-foreground">{masked ? 'Consent-restricted learner' : trainee.name}</p><p className="mt-1 text-meta text-muted-foreground">{trainee.traineeId} · {trainee.district} · {trainee.course}</p><p className="mt-1 text-meta text-muted-foreground">{trainee.trainingProvider}</p></div><div className="flex items-center gap-3"><ConsentBadge state={consent.consentStatus} />{masked ? <button type="button" title="Fields are masked because this learner has not granted active consent." aria-label="Why are fields masked?" onClick={() => setMaskSheet(true)} className="rounded-pill p-1 text-muted-foreground focus-visible:outline-2 focus-visible:outline-brand"><EyeOff aria-hidden="true" /></button> : null}</div></div></SectionCard>
    <SectionCard title="Lifecycle proof" description="This is the learner lifecycle, not the statewide five-stage programme funnel."><div className="flex flex-col gap-3 md:flex-row md:items-start">{lifecycle.map((step, index) => <div key={step} className="flex flex-1 items-center gap-2"><div className="flex min-w-0 flex-1 flex-col items-center gap-2 text-center"><span className={`flex size-9 items-center justify-center rounded-pill border ${lifecycleState[index] ? 'border-verified/40 bg-verified/10 text-verified' : 'border-border bg-muted text-muted-foreground'}`}>{lifecycleState[index] ? <Check aria-hidden="true" /> : <Clock3 aria-hidden="true" />}</span><span className="text-meta font-medium text-foreground">{step}</span></div>{index < lifecycle.length - 1 ? <span className="hidden text-border md:block">→</span> : null}</div>)}</div></SectionCard>
    <div className="grid gap-6 lg:grid-cols-2"><SectionCard title="Certification" description="Credential evidence from the training record."><div className="grid grid-cols-2 gap-4"><div><p className="text-meta text-muted-foreground">Certificate ID</p><p className="mt-1 font-mono text-sm text-foreground">{masked ? '••••••••' : trainee.certificate.certificateId}</p></div><div><p className="text-meta text-muted-foreground">NSQF level</p><p className="mt-1 font-serif text-2xl tabular-nums text-foreground">{masked ? '—' : trainee.certificate.nsqfLevel}</p></div><div><p className="text-meta text-muted-foreground">Issue date</p><p className="mt-1 text-sm text-foreground">{masked ? 'Consent required' : dates(trainee.certificate.issueDate)}</p></div><div><p className="text-meta text-muted-foreground">Training hours</p><p className="mt-1 font-serif text-2xl tabular-nums text-foreground">{masked ? '—' : trainee.trainingPeriod.hours}</p></div></div></SectionCard><SectionCard title="Recommended next skill" description="Recommendation, not a verified fact."><div className="flex items-start gap-3"><Sparkles className="mt-0.5 shrink-0 text-accent" aria-hidden="true" /><div><p className="font-medium text-foreground">Advanced digital maintenance logging</p><p className="mt-1 text-body leading-relaxed text-muted-foreground">Recommended from the learner’s current trade and observed wage progression.</p><StatusPill tone="pending" label="Recommendation" /></div></div></SectionCard></div>
    <ChartFrame title="Wage progression" description="Stepped wage updates show recorded changes, not an interpolated forecast." unit="INR per month" source="OutcomeEvent wage_update records"><div className="h-64 w-full" aria-label="Stepped wage progression"><ResponsiveContainer width="100%" height="100%"><AreaChart data={wageData} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><CartesianGrid stroke="var(--border)" vertical={false} /><XAxis dataKey="date" tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tickFormatter={(value) => `₹${Math.round(value / 1000)}k`} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} axisLine={false} tickLine={false} width={42} /><Tooltip formatter={(value) => money(Number(value))} contentStyle={{ background: 'var(--surface)', borderColor: 'var(--border)', borderRadius: 'var(--radius-control)' }} /><Area type="stepAfter" dataKey="wage" stroke={CHART_SERIES[0]} fill={CHART_SERIES[0]} fillOpacity={0.08} strokeWidth={2} /></AreaChart></ResponsiveContainer></div></ChartFrame>
    <SectionCard title="Employment timeline" description="A check icon means employer-verified; a clock means self-reported or awaiting verification."><div className="flex flex-col gap-3">{employmentEvents.map((event, index) => { const eventVerified = event.verifiedStatus === 'verified'; return <div key={`${event.eventDate}-${index}`} className="flex gap-3 border-l-2 border-border pl-4"><div className={`mt-1 flex size-7 shrink-0 items-center justify-center rounded-pill border ${eventVerified ? 'border-verified/40 bg-verified/10 text-verified' : 'border-pending/40 bg-pending/10 text-pending'}`}>{eventVerified ? <ShieldCheck aria-hidden="true" /> : <Clock3 aria-hidden="true" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="font-medium text-foreground">{event.employerName ?? 'Employer not recorded'}</p><p className="font-serif text-xl tabular-nums text-foreground">{event.monthlyWage ? money(event.monthlyWage) : 'Wage pending'}</p></div><p className="text-meta text-muted-foreground">{dates(event.eventDate)} · {event.jobRole ?? event.outcomeType.replaceAll('_', ' ')} · {eventVerified ? 'Employer verified' : 'Self-reported / pending'}</p></div></div>})}</div></SectionCard>
    <SectionCard title="Retention milestones" description="Unreached milestones are pending or not yet due, never failures."><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{milestones.map((milestone) => <div key={milestone.label} className="rounded-control border border-border bg-canvas p-4"><p className="text-meta text-muted-foreground">{milestone.label}</p><div className="mt-3 flex items-center gap-2">{milestone.state === 'met' ? <BadgeCheck className="text-verified" aria-hidden="true" /> : <Clock3 className="text-pending" aria-hidden="true" />}<span className="text-sm font-medium text-foreground">{milestone.state === 'not yet due' ? 'Not yet due' : milestone.state === 'met' ? 'Met' : 'Pending'}</span></div></div>)}</div></SectionCard>
    <DetailSheet open={maskSheet} onClose={() => setMaskSheet(false)} title="Privacy control" description="Consent-aware masking"><div className="flex flex-col gap-3"><EyeOff className="text-brand" aria-hidden="true" /><p className="text-body leading-relaxed text-foreground">This learner has not granted active consent for outcome details. Identifying fields remain masked deliberately; the record is not missing.</p></div></DetailSheet></main></AppShell>
}

void BriefcaseBusiness
void GraduationCap
void IndianRupee
void CHART_SEMANTIC
void useMemo
